# Generated by Django 2.2.4 on 2019-08-25 08:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('billing', '0002_auto_20190819_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingprofile',
            name='customer_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
