# Generated by Django 2.2.4 on 2019-08-26 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_charge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charge',
            old_name='outcame_type',
            new_name='outcome_type',
        ),
    ]
