# Generated by Django 2.2.4 on 2019-08-27 04:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('billing', '0008_auto_20190826_1552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='activate',
            new_name='active',
        ),
    ]
