# Generated by Django 2.2.4 on 2019-08-29 19:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingpreference',
            name='mailchimp_subscribed',
            field=models.NullBooleanField(),
        ),
    ]
