# Generated by Django 2.2.4 on 2019-08-29 20:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('marketing', '0002_marketingpreference_mailchimp_subscribed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketingpreference',
            old_name='update',
            new_name='updated',
        ),
    ]
