# Generated by Django 2.2.4 on 2019-08-19 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='oreder_id',
            new_name='order_id',
        ),
    ]
