# Generated by Django 2.2.4 on 2019-08-13 08:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0002_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='products/'),
        ),
    ]
