# Generated by Django 2.2.4 on 2019-08-14 05:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0007_remove_product_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
