# Generated by Django 2.2.4 on 2019-08-14 06:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0008_product_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
