# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-06-21 18:14
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_productfile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productfile',
            name='free',
        ),
        migrations.RemoveField(
            model_name='productfile',
            name='user_required',
        ),
        migrations.AlterField(
            model_name='productfile',
            name='file',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/mnt/c/Users/permi/source/repos/draft/2/static_cdn/protected_media'), upload_to=products.models.upload_product_file_loc),
        ),
    ]
