# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-07-02 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0018_auto_20200622_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='delivery',
            field=models.BooleanField(default=True),
        ),
    ]
